accounts:
# 帐号列表
- student-id: '12345678'  # 学号
  password: '123456'  # 登录密码
  # 地区, 前3个为地区代号, 后3个为描述, 地区代号在填报的网页里查
  region: [ '123456', '123456', '123456', '北京市', '北京市', '东城区' ]
notification:
  token: xxx

